management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

server:
  port: ${port:8080}

spring.flyway.baseline-on-migrate: true
